using System;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VolleyStats.Models;

namespace VolleyStats.Data
{
    /// <summary>
    /// Generates a portrait A4 PDF match report using QuestPDF.
    ///
    /// Layout (top → bottom, single page):
    ///   Page header (repeats): slim competition/league bar
    ///   Content:
    ///     – Match score hero (team names + set score)
    ///     – Match metadata row (date, time, city, hall, referees, spectators)
    ///     – Set-by-set results table
    ///     – Home team: player stats table + coach
    ///     – Away team: player stats table + coach
    ///     – Per-set breakdown (home | away, side-by-side)
    ///   Footer: "Generated by VolleyStats"
    ///
    /// Missing data fields (not yet in domain model):
    ///   – Match number / ID
    ///   – Individual set durations in seconds (currently stored as minutes int)
    ///   – Side-out %, break-point %, reception-to-point ratios
    ///   – Player votes / ratings
    /// </summary>
    public static class MatchReportPdfGenerator
    {
        // ── Colour palette ────────────────────────────────────────────────────
        private const string BrandBlue = "#2563EB";
        private const string DarkBlue  = "#1E3A5F";
        private const string LightGray = "#F1F5F9";
        private const string MedGray   = "#64748B";
        private const string DarkText  = "#1E293B";
        private const string White     = "#FFFFFF";
        private const string AwayGreen = "#15803D";
        private const string ServeBlue = "#1D4ED8";
        private const string RecTeal   = "#0F766E";
        private const string AtkPurple = "#7E22CE";
        private const string BlkAmber  = "#92400E";
        private const string RowAlt    = "#F8FAFC";
        private const string Separator = "#CBD5E1";

        // ── Entry point ───────────────────────────────────────────────────────
        public static void Generate(MatchReportData data, string outputPath)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);          // portrait
                    page.MarginHorizontal(16);
                    page.MarginVertical(10);
                    page.DefaultTextStyle(x => x.FontSize(7f).FontColor(DarkText));

                    page.Header().Element(h => ComposePageBanner(h, data));
                    page.Content().Element(c => ComposeContent(c, data));
                    page.Footer().AlignCenter().Text(t =>
                        t.Span("Generated by VolleyStats").FontSize(5.5f).FontColor(MedGray));
                });
            }).GeneratePdf(outputPath);
        }

        // ── Page banner (repeats on every page) ───────────────────────────────
        private static void ComposePageBanner(IContainer container, MatchReportData data)
        {
            var match = data.Match;
            var league = match.Info?.League ?? "";
            var phase  = match.Info?.Phase  ?? "";
            var day    = match.Info?.Day;
            var title  = $"{league}  {phase}".Trim();
            if (day > 0) title += $"  ·  Round {day}";

            container.Background(BrandBlue).PaddingHorizontal(10).PaddingVertical(3).Row(row =>
            {
                row.RelativeItem().AlignMiddle()
                    .Text(title).FontSize(7f).FontColor(White).Bold();

                row.AutoItem().AlignCenter().PaddingHorizontal(12).AlignMiddle()
                    .Text("MATCH REPORT").FontSize(8f).Bold().FontColor(White);

                row.RelativeItem().AlignRight().AlignMiddle()
                    .Text(data.IsTeamOnly ? $"{data.MatchesAggregated} match(es) aggregated" : "")
                    .FontSize(6f).FontColor("#CBD5E1");
            });
        }

        // ── Content (score hero + metadata + sets + team tables) ─────────────
        private static void ComposeContent(IContainer container, MatchReportData data)
        {
            container.Column(col =>
            {
                if (!data.IsTeamOnly)
                {
                    ComposeScoreHero(col, data.Match);
                    ComposeMetadataBar(col, data.Match);
                    ComposeSetResults(col, data.Match);
                    col.Item().LineHorizontal(0.5f).LineColor(Separator);
                }

                int setCount = data.IsTeamOnly ? 0 : (data.Match.Sets?.Count ?? 0);

                col.Item().PaddingTop(4).Element(c =>
                    ComposeTeamSection(c, data.HomeStats, isHome: true, setCount,
                        oppStats: data.IsTeamOnly ? null : data.AwayStats));

                if (!data.IsTeamOnly)
                {
                    col.Item().PaddingTop(5).Element(c =>
                        ComposeTeamSection(c, data.AwayStats, isHome: false, setCount,
                            oppStats: data.HomeStats));

                    if (data.HomeStats.SetStats.Count > 0 || data.AwayStats.SetStats.Count > 0)
                        col.Item().PaddingTop(5).Element(c => ComposePerSetBreakdown(c, data));
                }
            });
        }

        // ── Score hero ────────────────────────────────────────────────────────
        private static void ComposeScoreHero(ColumnDescriptor col, Match match)
        {
            col.Item().Background(DarkBlue).PaddingHorizontal(10).PaddingVertical(5).Row(row =>
            {
                row.RelativeItem().AlignLeft().AlignMiddle()
                    .Text(match.HomeTeam.Name).FontSize(10).Bold().FontColor(White);

                row.AutoItem().PaddingHorizontal(16).AlignMiddle()
                    .Text($"{match.HomeTeam.SetsWon}  :  {match.AwayTeam.SetsWon}")
                    .FontSize(15).Bold().FontColor(White);

                row.RelativeItem().AlignRight().AlignMiddle()
                    .Text(match.AwayTeam.Name).FontSize(10).Bold().FontColor(White);
            });
        }

        // ── Match metadata bar ────────────────────────────────────────────────
        private static void ComposeMetadataBar(ColumnDescriptor col, Match match)
        {
            col.Item().Background(LightGray).PaddingHorizontal(10).PaddingVertical(3).Row(row =>
            {
                var info = match.Info;
                var more = match.MoreInfo;

                row.RelativeItem().Text(t =>
                {
                    if (info != null)
                    {
                        Kv(t, "Date", info.Date.ToString("dd.MM.yyyy"));
                        Kv(t, "Time", info.Time.ToString("HH:mm"));
                    }
                    if (!string.IsNullOrEmpty(more?.City))
                        Kv(t, "City", more.City);
                    if (!string.IsNullOrEmpty(more?.Hall))
                        Kv(t, "Hall", more.Hall);
                });

                row.AutoItem().AlignRight().Text(t =>
                {
                    if (!string.IsNullOrEmpty(more?.Referees))
                        Kv(t, "Referees", more.Referees);
                    if (more?.Spectators > 0)
                        Kv(t, "Spectators", more.Spectators.ToString());
                });
            });
        }

        private static void Kv(TextDescriptor t, string label, string? value)
        {
            if (string.IsNullOrEmpty(value)) return;
            t.Span($"{label}: ").SemiBold().FontSize(6.5f);
            t.Span($"{value}  ").FontSize(6.5f);
        }

        // ── Set results table ─────────────────────────────────────────────────
        private static void ComposeSetResults(ColumnDescriptor col, Match match)
        {
            if (match.Sets == null || match.Sets.Count == 0) return;

            int maxPartials = match.Sets.Max(s => s.PartialScores?.Count ?? 0);
            maxPartials = Math.Min(maxPartials, 4);

            col.Item().PaddingHorizontal(2).PaddingTop(4).PaddingBottom(3).Column(inner =>
            {
                inner.Item().PaddingBottom(2)
                    .Text("SET RESULTS").FontSize(5.5f).Bold().FontColor(MedGray);

                inner.Item().Table(table =>
                {
                    table.ColumnsDefinition(cols =>
                    {
                        cols.ConstantColumn(24);  // Set #
                        cols.ConstantColumn(34);  // Duration
                        cols.ConstantColumn(42);  // Final score
                        for (int i = 0; i < maxPartials; i++)
                            cols.ConstantColumn(34);  // Partial scores
                    });

                    table.Header(header =>
                    {
                        HdrCell(header, "Set");
                        HdrCell(header, "Dur.");
                        HdrCell(header, "Score");
                        for (int i = 0; i < maxPartials; i++)
                            HdrCell(header, $"P{i + 1}");
                    });

                    int totalDur = 0, totalHome = 0, totalAway = 0;

                    for (int i = 0; i < match.Sets.Count; i++)
                    {
                        var set   = match.Sets[i];
                        var bg    = i % 2 == 0 ? White : RowAlt;
                        var parts = set.PartialScores
                            ?? new System.Collections.Generic.List<MatchScore>();

                        totalDur += set.Duration;

                        DCell(table, bg, (i + 1).ToString(), bold: true);
                        DCell(table, bg, FormatMinutes(set.Duration));

                        if (set.FinalScore != null)
                        {
                            totalHome += set.FinalScore.HomeTeamScore;
                            totalAway += set.FinalScore.AwayTeamScore;
                            DCell(table, bg,
                                $"{set.FinalScore.HomeTeamScore}–{set.FinalScore.AwayTeamScore}",
                                bold: true);
                        }
                        else
                        {
                            DCell(table, bg, "–");
                        }

                        for (int p = 0; p < maxPartials; p++)
                        {
                            DCell(table, bg,
                                p < parts.Count
                                    ? $"{parts[p].HomeTeamScore}–{parts[p].AwayTeamScore}"
                                    : "");
                        }
                    }

                    // Totals row
                    DCell(table, LightGray, "Total", bold: true);
                    DCell(table, LightGray, FormatMinutes(totalDur), bold: true);
                    DCell(table, LightGray, $"{totalHome}–{totalAway}", bold: true);
                    for (int p = 0; p < maxPartials; p++)
                        DCell(table, LightGray, "");
                });
            });
        }

        // ── Team section: header bar + player table + summary strip + staff ─────
        //
        private static void ComposeTeamSection(IContainer container, TeamStats stats, bool isHome, int setCount,
            TeamStats? oppStats = null)
        {
            var headerBg = isHome ? BrandBlue : AwayGreen;

            container.Column(col =>
            {
                // Team name bar
                col.Item().Background(headerBg).PaddingHorizontal(7).PaddingVertical(3)
                    .Text(stats.TeamName.ToUpperInvariant())
                    .FontSize(7.5f).Bold().FontColor(White);

                // Player statistics table
                col.Item().Element(c => ComposePlayerTable(c, stats, setCount));

                // Points-by-category summary strip
                int oppErrors = oppStats != null
                    ? oppStats.AtkErr + oppStats.BlkPoor + oppStats.ServeErr + oppStats.SetErr + oppStats.FreeBallErr
                    : stats.OpponentErrors;
                int grandTotal = stats.TotalPoints + oppErrors;
                col.Item().Background("#EEF2FB")
                    .PaddingHorizontal(7).PaddingVertical(2).Text(t =>
                {
                    t.Span("Points won: ").FontSize(5.5f).SemiBold().FontColor(MedGray);
                    t.Span($"Serve {stats.ServePts}").FontSize(5.5f).Bold().FontColor(ServeBlue);
                    t.Span("   ·   ").FontSize(5.5f).FontColor(MedGray);
                    t.Span($"Attack {stats.AtkPts}").FontSize(5.5f).Bold().FontColor(AtkPurple);
                    t.Span("   ·   ").FontSize(5.5f).FontColor(MedGray);
                    t.Span($"Block {stats.BlkPts}").FontSize(5.5f).Bold().FontColor(BlkAmber);
                    t.Span("   ·   ").FontSize(5.5f).FontColor(MedGray);
                    t.Span($"Opp. errors {oppErrors}").FontSize(5.5f).FontColor(MedGray);
                    t.Span($"   Total: {grandTotal}").FontSize(6f).Bold().FontColor(DarkBlue);
                });

                // Coaching staff
                if (!string.IsNullOrWhiteSpace(stats.CoachName) ||
                    !string.IsNullOrWhiteSpace(stats.AssistantCoach))
                {
                    col.Item().PaddingTop(2).PaddingHorizontal(3).Text(t =>
                    {
                        if (!string.IsNullOrEmpty(stats.CoachName))
                        {
                            t.Span("Coach: ").SemiBold().FontSize(6f);
                            t.Span(stats.CoachName).FontSize(6f);
                        }
                        if (!string.IsNullOrEmpty(stats.AssistantCoach))
                        {
                            t.Span("   Asst: ").SemiBold().FontSize(6f);
                            t.Span(stats.AssistantCoach).FontSize(6f);
                        }
                    });
                }
            });
        }

        // ── Player statistics table ───────────────────────────────────────────
        //
        // Column layout — all RelativeColumn so the table stretches to full page width.
        // Proportions mirror the original fixed-pixel ratios.
        //   Identity: # (14) · L (8) · Name (75)                          = 97
        //   Set positions: setCount × 13
        //   Serve:     Tot/Err/Pts    3 × 15                               = 45
        //   Reception: Tot/Err/Pos/Exc 15+15+20+20                        = 70
        //   Attack:    Tot/Err/Blo/Pts/% 4×15+19                          = 79
        //   Block:     Pts 15                                              = 15
        //   Total pts: 13                                                  = 13
        //   W-L:       18  (won−lost, can be negative)                    = 18
        private static void ComposePlayerTable(IContainer container, TeamStats stats, int setCount)
        {
            // Colour for set-position column group header
            const string SetPosBg = "#475569";

            container.Table(table =>
            {
                table.ColumnsDefinition(cols =>
                {
                    cols.RelativeColumn(14);   // #
                    cols.RelativeColumn(8);    // L (libero marker)
                    cols.RelativeColumn(75);   // Name
                    for (int s = 0; s < setCount; s++)
                        cols.RelativeColumn(13);   // per-set position column
                    // Serve
                    cols.RelativeColumn(15); cols.RelativeColumn(15); cols.RelativeColumn(15);
                    // Reception
                    cols.RelativeColumn(15); cols.RelativeColumn(15);
                    cols.RelativeColumn(20); cols.RelativeColumn(20);
                    // Attack
                    cols.RelativeColumn(15); cols.RelativeColumn(15);
                    cols.RelativeColumn(15); cols.RelativeColumn(15); cols.RelativeColumn(19);
                    // Block
                    cols.RelativeColumn(15);
                    // Total points
                    cols.RelativeColumn(13);
                    // W-L (won minus lost, can be negative)
                    cols.RelativeColumn(18);
                });

                // ── Header rows ──────────────────────────────────────────────
                table.Header(header =>
                {
                    var g = TextStyle.Default.FontSize(5.5f).FontColor(White).Bold();

                    // Row 1 — skill-group colour bands
                    header.Cell().ColumnSpan(3).Background(DarkBlue)
                        .PaddingVertical(1).PaddingHorizontal(2).Text("").Style(g);

                    if (setCount > 0)
                        header.Cell().ColumnSpan((uint)setCount).Background(SetPosBg)
                            .PaddingVertical(1).PaddingHorizontal(2).AlignCenter()
                            .Text("Position by set").Style(g);

                    header.Cell().ColumnSpan(3).Background(ServeBlue)
                        .PaddingVertical(1).PaddingHorizontal(2).AlignCenter().Text("Serve").Style(g);
                    header.Cell().ColumnSpan(4).Background(RecTeal)
                        .PaddingVertical(1).PaddingHorizontal(2).AlignCenter().Text("Reception").Style(g);
                    header.Cell().ColumnSpan(5).Background(AtkPurple)
                        .PaddingVertical(1).PaddingHorizontal(2).AlignCenter().Text("Attack").Style(g);
                    header.Cell().ColumnSpan(1).Background(BlkAmber)
                        .PaddingVertical(1).PaddingHorizontal(2).AlignCenter().Text("Blk").Style(g);
                    header.Cell().ColumnSpan(2).Background(DarkBlue)
                        .PaddingVertical(1).PaddingHorizontal(2).AlignCenter().Text("Pts / W-L").Style(g);

                    // Row 2 — column sub-labels
                    SHdr(header, "#"); SHdr(header, "L");
                    header.Cell().Background(LightGray).Padding(1).AlignLeft()
                        .Text("Name").FontSize(5.5f).SemiBold();
                    for (int s = 1; s <= setCount; s++)
                        SHdr(header, $"S{s}");
                    SHdr(header, "Tot"); SHdr(header, "Err"); SHdr(header, "Pts");
                    SHdr(header, "Tot"); SHdr(header, "Err"); SHdr(header, "Pos"); SHdr(header, "Exc");
                    SHdr(header, "Tot"); SHdr(header, "Err"); SHdr(header, "Blo"); SHdr(header, "Pts"); SHdr(header, "%");
                    SHdr(header, "Pts");
                    SHdr(header, "Tot"); SHdr(header, "W-L");
                });

                // ── Player rows ───────────────────────────────────────────────
                bool alt = false;
                foreach (var ps in stats.Players.OrderBy(p => p.JerseyNumber))
                {
                    if (ps.ServeTot == 0 && ps.RecTot == 0 && ps.AtkTot == 0 && ps.BlkPts == 0)
                        continue;

                    var bg = alt ? RowAlt : White;
                    alt = !alt;

                    DCell(table, bg, ps.JerseyNumber.ToString(), bold: true);
                    table.Cell().Background(bg).PaddingVertical(1).PaddingHorizontal(1).AlignCenter()
                        .Text(ps.IsLibero ? "L" : "").FontSize(6f).FontColor("#DC2626");
                    table.Cell().Background(bg).PaddingVertical(1).PaddingHorizontal(2).AlignLeft()
                        .Text(ps.Name).FontSize(6.5f);

                    // Per-set starting zone: zone number for starters, · for subs, empty if didn't play
                    for (int s = 1; s <= setCount; s++)
                    {
                        string zone;
                        if (ps.SetZones.TryGetValue(s, out var z))
                            zone = z.ToString();
                        else if (ps.SetsPlayed.Contains(s))
                            zone = "·";   // entered as substitute
                        else
                            zone = "";    // did not play this set

                        table.Cell().Background(bg).PaddingVertical(1).PaddingHorizontal(1)
                            .AlignCenter().Text(zone).FontSize(6f).FontColor(MedGray);
                    }

                    NCell(table, bg, ps.ServeTot); NCell(table, bg, ps.ServeErr); NCell(table, bg, ps.ServePts);
                    NCell(table, bg, ps.RecTot);   NCell(table, bg, ps.RecErr);
                    DCell(table, bg, ps.RecPosPercent);
                    DCell(table, bg, ps.RecTot > 0 && ps.RecExc > 0 ? $"{ps.RecExc * 100 / ps.RecTot}%" : ".");
                    NCell(table, bg, ps.AtkTot); NCell(table, bg, ps.AtkErr);
                    NCell(table, bg, ps.AtkBlo); NCell(table, bg, ps.AtkPts);
                    DCell(table, bg, ps.AtkPtsPercent);
                    NCell(table, bg, ps.BlkPts);
                    NCell(table, bg, ps.TotalPoints, bold: true);
                    int wl = (ps.ServePts + ps.AtkPts + ps.BlkPts) - (ps.ServeErr + ps.AtkErr + ps.AtkBlo);
                    WLCell(table, bg, wl);
                }

                // ── Team total row ────────────────────────────────────────────
                int idColSpan = 3 + setCount;  // # + L + Name + set columns
                table.Cell().ColumnSpan((uint)idColSpan).Background(DarkBlue)
                    .PaddingVertical(1).PaddingHorizontal(4).AlignLeft()
                    .Text("Team Total").FontSize(6.5f).Bold().FontColor(White);

                TCell(table, stats.ServeTot); TCell(table, stats.ServeErr); TCell(table, stats.ServePts);
                TCell(table, stats.RecTot);   TCell(table, stats.RecErr);
                TTxt(table, stats.RecPosPercent);
                TTxt(table, stats.RecTot > 0 && stats.RecExc > 0
                    ? $"{stats.RecExc * 100 / stats.RecTot}%" : ".");
                TCell(table, stats.AtkTot); TCell(table, stats.AtkErr);
                TCell(table, stats.AtkBlo); TCell(table, stats.AtkPts);
                TTxt(table, stats.AtkPtsPercent);
                TCell(table, stats.BlkPts);
                TCell(table, stats.ServePts + stats.AtkPts + stats.BlkPts, highlight: true);
                int teamWl = (stats.ServePts + stats.AtkPts + stats.BlkPts) - (stats.ServeErr + stats.AtkErr + stats.AtkBlo);
                TWLCell(table, teamWl);
            });
        }

        // ── Per-set breakdown (two columns) ───────────────────────────────────
        private static void ComposePerSetBreakdown(IContainer container, MatchReportData data)
        {
            container.Column(col =>
            {
                col.Item().PaddingBottom(2)
                    .Text("PER-SET BREAKDOWN").FontSize(5.5f).Bold().FontColor(MedGray);

                col.Item().Row(row =>
                {
                    row.RelativeItem().PaddingRight(3)
                        .Element(c => ComposeSetStatsTable(c, data.HomeStats, isHome: true));
                    row.RelativeItem().PaddingLeft(3)
                        .Element(c => ComposeSetStatsTable(c, data.AwayStats, isHome: false));
                });
            });
        }

        private static void ComposeSetStatsTable(IContainer container, TeamStats stats, bool isHome)
        {
            var hdrBg = isHome ? BrandBlue : AwayGreen;

            container.Column(col =>
            {
                col.Item().Background(hdrBg).PaddingHorizontal(5).PaddingVertical(2)
                    .Text(stats.TeamName).FontSize(6.5f).Bold().FontColor(White);

                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(cols =>
                    {
                        cols.RelativeColumn(20); // Set label
                        // Serve: Tot / Err / Pts
                        cols.RelativeColumn(15); cols.RelativeColumn(15); cols.RelativeColumn(15);
                        // Reception: Tot / Err / Pos%
                        cols.RelativeColumn(15); cols.RelativeColumn(15); cols.RelativeColumn(22);
                        // Attack: Tot / Err / Blk / Pts
                        cols.RelativeColumn(15); cols.RelativeColumn(15);
                        cols.RelativeColumn(15); cols.RelativeColumn(15);
                        // Block
                        cols.RelativeColumn(15);
                    });

                    table.Header(header =>
                    {
                        var g = TextStyle.Default.FontSize(5f).FontColor(White).Bold();
                        header.Cell().Background(DarkBlue).Padding(1).Text("").Style(g);
                        header.Cell().ColumnSpan(3).Background(ServeBlue).Padding(1).AlignCenter().Text("Serve").Style(g);
                        header.Cell().ColumnSpan(3).Background(RecTeal).Padding(1).AlignCenter().Text("Rec.").Style(g);
                        header.Cell().ColumnSpan(4).Background(AtkPurple).Padding(1).AlignCenter().Text("Attack").Style(g);
                        header.Cell().Background(BlkAmber).Padding(1).AlignCenter().Text("Blk").Style(g);

                        SSHdr(header, "");
                        SSHdr(header, "T"); SSHdr(header, "E"); SSHdr(header, "P");
                        SSHdr(header, "T"); SSHdr(header, "E"); SSHdr(header, "Pos");
                        SSHdr(header, "T"); SSHdr(header, "E"); SSHdr(header, "Blk"); SSHdr(header, "P");
                        SSHdr(header, "P");
                    });

                    bool alt = false;
                    foreach (var ss in stats.SetStats)
                    {
                        var bg = alt ? RowAlt : White;
                        alt = !alt;

                        DCell(table, bg, $"S{ss.SetNumber}", bold: true);
                        DCell(table, bg, Fmt(ss.ServeTot)); DCell(table, bg, Fmt(ss.ServeErr)); DCell(table, bg, Fmt(ss.ServePts));
                        DCell(table, bg, Fmt(ss.RecTot));   DCell(table, bg, Fmt(ss.RecErr));
                        DCell(table, bg, ss.RecTot > 0 ? $"{ss.RecPos * 100 / ss.RecTot}%" : ".");
                        DCell(table, bg, Fmt(ss.AtkTot)); DCell(table, bg, Fmt(ss.AtkErr));
                        DCell(table, bg, Fmt(ss.AtkBlo)); DCell(table, bg, Fmt(ss.AtkPts));
                        DCell(table, bg, Fmt(ss.BlkPts));
                    }
                });
            });
        }

        // ── Cell helpers ──────────────────────────────────────────────────────

        // Header cell in set-results table.Header() block
        private static void HdrCell(TableCellDescriptor h, string text)
        {
            h.Cell().Background(LightGray).Border(0.5f).BorderColor(Separator)
                .Padding(1).AlignCenter().Text(text).FontSize(6f).SemiBold();
        }

        // Sub-label row cell in player table header
        private static void SHdr(TableCellDescriptor h, string text)
        {
            h.Cell().Background(LightGray).Border(0.5f).BorderColor("#E2E8F0")
                .Padding(1).AlignCenter().Text(text).FontSize(5.5f).SemiBold().FontColor(DarkText);
        }

        // Tiny sub-label for the compact per-set table
        private static void SSHdr(TableCellDescriptor h, string text)
        {
            h.Cell().Background(LightGray).Padding(1).AlignCenter()
                .Text(text).FontSize(5f).SemiBold().FontColor(DarkText);
        }

        // Standard centered data cell (regular rows)
        private static void DCell(TableDescriptor t, string bg, string text, bool bold = false)
        {
            var cell = t.Cell().Background(bg).PaddingVertical(1).PaddingHorizontal(2)
                .AlignCenter().Text(text).FontSize(6.5f);
            if (bold) cell.Bold();
        }

        // Numeric cell — shows "." when zero
        private static void NCell(TableDescriptor t, string bg, int value, bool bold = false)
        {
            DCell(t, bg, value > 0 ? value.ToString() : ".", bold);
        }

        // Team total numeric cell (dark blue background, white bold text)
        private static void TCell(TableDescriptor t, int value, bool highlight = false)
        {
            var bg = highlight ? "#162D4A" : DarkBlue;
            t.Cell().Background(bg).PaddingVertical(1).PaddingHorizontal(2).AlignCenter()
                .Text(value > 0 ? value.ToString() : ".").FontSize(6.5f).Bold().FontColor(White);
        }

        // Team total text cell (for percentage strings)
        private static void TTxt(TableDescriptor t, string text)
        {
            t.Cell().Background(DarkBlue).PaddingVertical(1).PaddingHorizontal(2).AlignCenter()
                .Text(text).FontSize(6.5f).Bold().FontColor(White);
        }

        // Player row W-L cell: green for positive, red for negative
        private static void WLCell(TableDescriptor t, string bg, int wl)
        {
            string text  = wl > 0 ? $"+{wl}" : wl == 0 ? "." : wl.ToString();
            string color = wl > 0 ? "#16A34A" : wl < 0 ? "#DC2626" : MedGray;
            t.Cell().Background(bg).PaddingVertical(1).PaddingHorizontal(2).AlignCenter()
                .Text(text).FontSize(6.5f).Bold().FontColor(color);
        }

        // Team total W-L cell (on DarkBlue background)
        private static void TWLCell(TableDescriptor t, int wl)
        {
            string text  = wl > 0 ? $"+{wl}" : wl == 0 ? "." : wl.ToString();
            string color = wl > 0 ? "#86EFAC" : wl < 0 ? "#FCA5A5" : White;
            t.Cell().Background(DarkBlue).PaddingVertical(1).PaddingHorizontal(2).AlignCenter()
                .Text(text).FontSize(6.5f).Bold().FontColor(color);
        }

        // ── Formatting helpers ────────────────────────────────────────────────

        private static string FormatMinutes(int totalMinutes)
        {
            if (totalMinutes <= 0) return "–";
            return $"{totalMinutes / 60}:{totalMinutes % 60:D2}";
        }

        private static string Fmt(int v) => v > 0 ? v.ToString() : ".";
    }
}
