using System;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using VolleyStats.Models;

namespace VolleyStats.Data
{
    public static class MatchReportPdfGenerator
    {
        private const string BrandBlue = "#2563EB";
        private const string DarkBlue = "#1E3A5F";
        private const string LightGray = "#F1F5F9";
        private const string MedGray = "#64748B";
        private const string DarkText = "#1E293B";
        private const string White = "#FFFFFF";
        private const string GreenAccent = "#16A34A";

        public static void Generate(MatchReportData data, string outputPath)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var match = data.Match;

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4.Landscape());
                    page.MarginHorizontal(25);
                    page.MarginVertical(20);
                    page.DefaultTextStyle(x => x.FontSize(8).FontColor(DarkText));

                    page.Header().Element(h => ComposeHeader(h, match, data));
                    page.Content().Element(c => ComposeContent(c, data));
                    page.Footer().AlignCenter().Text(t =>
                    {
                        t.Span("Generated by VolleyStats").FontSize(7).FontColor(MedGray);
                    });
                });
            }).GeneratePdf(outputPath);
        }

        private static void ComposeHeader(IContainer container, Match match, MatchReportData data)
        {
            container.Column(col =>
            {
                // League + title bar
                col.Item().Background(BrandBlue).Padding(12).Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        var league = match.Info?.League ?? "";
                        var phase = match.Info?.Phase ?? "";
                        var day = match.Info?.Day;
                        c.Item().Text($"{league} {phase}").FontSize(9).FontColor(White).Bold();
                        if (day > 0)
                            c.Item().Text($"Day {day}").FontSize(7).FontColor("#CBD5E1");
                    });

                    row.RelativeItem().AlignCenter().Text("Match Report").FontSize(14).Bold().FontColor(White);

                    row.RelativeItem().AlignRight().Column(c =>
                    {
                        c.Item().AlignRight().Text($"{match.HomeTeam.Name}  {match.HomeTeam.SetsWon} : {match.AwayTeam.SetsWon}  {match.AwayTeam.Name}")
                            .FontSize(12).Bold().FontColor(White);
                    });
                });

                // Match info row
                col.Item().Background(LightGray).PaddingHorizontal(12).PaddingVertical(6).Row(row =>
                {
                    var info = match.Info;
                    var more = match.MoreInfo;
                    row.RelativeItem().Text(t =>
                    {
                        t.Span("Date: ").SemiBold();
                        t.Span($"{info?.Date:MM/dd/yyyy}  ");
                        t.Span("Time: ").SemiBold();
                        t.Span($"{info?.Time:HH:mm}  ");
                        t.Span("City: ").SemiBold();
                        t.Span($"{more?.City ?? "-"}  ");
                        t.Span("Hall: ").SemiBold();
                        t.Span($"{more?.Hall ?? "-"}  ");
                    });
                    row.RelativeItem().AlignRight().Text(t =>
                    {
                        t.Span("Referees: ").SemiBold();
                        t.Span($"{more?.Referees ?? "-"}  ");
                        if (more?.Spectators > 0)
                        {
                            t.Span("Spectators: ").SemiBold();
                            t.Span($"{more.Spectators}");
                        }
                    });
                });

                // Set scores
                col.Item().PaddingHorizontal(12).PaddingVertical(4).Row(row =>
                {
                    row.RelativeItem().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.ConstantColumn(40);  // Set label
                            cols.ConstantColumn(55);  // Duration
                            for (int i = 0; i < 3; i++)
                                cols.ConstantColumn(55); // Partial scores
                            cols.ConstantColumn(55);  // Final score
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Set").Bold().FontSize(7);
                            header.Cell().Text("Duration").Bold().FontSize(7);
                            header.Cell().Text("Partial").Bold().FontSize(7);
                            header.Cell().Text("Partial").Bold().FontSize(7);
                            header.Cell().Text("Partial").Bold().FontSize(7);
                            header.Cell().Text("Score").Bold().FontSize(7);
                        });

                        if (match.Sets != null)
                        {
                            int totalDuration = 0;
                            int totalHome = 0, totalAway = 0;

                            for (int i = 0; i < match.Sets.Count; i++)
                            {
                                var set = match.Sets[i];
                                totalDuration += set.Duration;
                                table.Cell().Text($"{i + 1}").FontSize(8);
                                int mins = set.Duration;
                                table.Cell().Text($"0:{mins:D2}").FontSize(8);

                                var partials = set.PartialScores ?? new System.Collections.Generic.List<MatchScore>();
                                for (int p = 0; p < 3; p++)
                                {
                                    if (p < partials.Count)
                                        table.Cell().Text($"{partials[p].HomeTeamScore}-{partials[p].AwayTeamScore}").FontSize(8);
                                    else
                                        table.Cell().Text("").FontSize(8);
                                }

                                if (set.FinalScore != null)
                                {
                                    totalHome += set.FinalScore.HomeTeamScore;
                                    totalAway += set.FinalScore.AwayTeamScore;
                                    table.Cell().Text($"{set.FinalScore.HomeTeamScore}-{set.FinalScore.AwayTeamScore}").Bold().FontSize(8);
                                }
                                else
                                {
                                    table.Cell().Text("").FontSize(8);
                                }
                            }

                            // Total row
                            table.Cell().Text("").FontSize(8);
                            int totalMins = totalDuration;
                            table.Cell().Text($"{totalMins / 60}:{totalMins % 60:D2}").Bold().FontSize(8);
                            table.Cell().Text("").FontSize(8);
                            table.Cell().Text("").FontSize(8);
                            table.Cell().Text("").FontSize(8);
                            table.Cell().Text($"{totalHome}  {totalAway}").Bold().FontSize(8);
                        }
                    });
                });

                col.Item().PaddingBottom(4).LineHorizontal(1).LineColor("#E2E8F0");
            });
        }

        private static void ComposeContent(IContainer container, MatchReportData data)
        {
            container.Row(row =>
            {
                row.RelativeItem().PaddingRight(8).Element(c => ComposeTeamTable(c, data.HomeStats, data.Match.HomePlayers, true));
                row.RelativeItem().PaddingLeft(8).Element(c => ComposeTeamTable(c, data.AwayStats, data.Match.AwayPlayers, false));
            });
        }

        private static void ComposeTeamTable(IContainer container, TeamStats stats, System.Collections.Generic.List<MatchPlayer> players, bool isHome)
        {
            var headerColor = isHome ? BrandBlue : GreenAccent;

            container.Column(col =>
            {
                // Team name header
                col.Item().Background(headerColor).Padding(6).Text(stats.TeamName).Bold().FontSize(10).FontColor(White);

                // Player stats table
                col.Item().Table(table =>
                {
                    table.ColumnsDefinition(cols =>
                    {
                        cols.ConstantColumn(18);  // #
                        cols.ConstantColumn(8);   // L
                        cols.RelativeColumn(1.5f); // Name
                        // Serve: Tot Err Pts
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        // Reception: Tot Err Pos% (Exc%)
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(30);
                        cols.ConstantColumn(30);
                        // Attack: Tot Err Blo Pts Pts%
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(28);
                        // Block pts
                        cols.ConstantColumn(22);
                    });

                    // Column group headers
                    table.Header(header =>
                    {
                        var cellStyle = TextStyle.Default.FontSize(6).FontColor(White);

                        header.Cell().ColumnSpan(3).Background(DarkBlue).Padding(2).Text("").Style(cellStyle);

                        header.Cell().ColumnSpan(3).Background("#1E40AF").Padding(2).AlignCenter()
                            .Text("Serve").Style(cellStyle).Bold();

                        header.Cell().ColumnSpan(4).Background("#0F766E").Padding(2).AlignCenter()
                            .Text("Reception").Style(cellStyle).Bold();

                        header.Cell().ColumnSpan(5).Background("#9333EA").Padding(2).AlignCenter()
                            .Text("Attack").Style(cellStyle).Bold();

                        header.Cell().ColumnSpan(1).Background("#B45309").Padding(2).AlignCenter()
                            .Text("BK").Style(cellStyle).Bold();

                        // Sub-headers
                        foreach (var label in new[] { "#", "", "Name", "Tot", "Err", "Pts", "Tot", "Err", "Pos%", "(Exc%)", "Tot", "Err", "Blo", "Pts", "Pts%", "Pts" })
                            header.Cell().Background(LightGray).Padding(2).AlignCenter().Text(label).FontSize(6).SemiBold();
                    });

                    // Player rows
                    bool alt = false;
                    foreach (var ps in stats.Players.OrderBy(p => p.JerseyNumber))
                    {
                        var bg = alt ? "#F8FAFC" : White;
                        alt = !alt;

                        table.Cell().Background(bg).Padding(2).Text($"{ps.JerseyNumber}").FontSize(7).Bold();
                        table.Cell().Background(bg).Padding(2).Text(ps.IsLibero ? "L" : "").FontSize(6).FontColor("#DC2626");
                        table.Cell().Background(bg).Padding(2).Text(ps.Name).FontSize(7);

                        NumCell(table, ps.ServeTot, bg);
                        NumCell(table, ps.ServeErr, bg);
                        NumCell(table, ps.ServePts, bg);

                        NumCell(table, ps.RecTot, bg);
                        NumCell(table, ps.RecErr, bg);
                        table.Cell().Background(bg).Padding(2).AlignCenter().Text(ps.RecPosPercent).FontSize(7);
                        table.Cell().Background(bg).Padding(2).AlignCenter().Text(ps.RecExcPercent).FontSize(7);

                        NumCell(table, ps.AtkTot, bg);
                        NumCell(table, ps.AtkErr, bg);
                        NumCell(table, ps.AtkBlo, bg);
                        NumCell(table, ps.AtkPts, bg);
                        table.Cell().Background(bg).Padding(2).AlignCenter().Text(ps.AtkPtsPercent).FontSize(7);

                        NumCell(table, ps.BlkPts, bg);
                    }

                    // Team total row
                    table.Cell().ColumnSpan(3).Background(DarkBlue).Padding(2).Text("Team Total").FontSize(7).Bold().FontColor(White);
                    NumCellBold(table, stats.ServeTot);
                    NumCellBold(table, stats.ServeErr);
                    NumCellBold(table, stats.ServePts);
                    NumCellBold(table, stats.RecTot);
                    NumCellBold(table, stats.RecErr);
                    table.Cell().Background(DarkBlue).Padding(2).AlignCenter().Text(stats.RecPosPercent).FontSize(7).Bold().FontColor(White);
                    table.Cell().Background(DarkBlue).Padding(2).AlignCenter().Text(stats.RecExcPercent).FontSize(7).Bold().FontColor(White);
                    NumCellBold(table, stats.AtkTot);
                    NumCellBold(table, stats.AtkErr);
                    NumCellBold(table, stats.AtkBlo);
                    NumCellBold(table, stats.AtkPts);
                    table.Cell().Background(DarkBlue).Padding(2).AlignCenter().Text(stats.AtkPtsPercent).FontSize(7).Bold().FontColor(White);
                    NumCellBold(table, stats.BlkPts);
                });

                // Per-set breakdown
                col.Item().PaddingTop(4).Table(table =>
                {
                    table.ColumnsDefinition(cols =>
                    {
                        cols.ConstantColumn(40); // label
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(30);
                        cols.ConstantColumn(30);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(22);
                        cols.ConstantColumn(28);
                        cols.ConstantColumn(22);
                    });

                    foreach (var ss in stats.SetStats)
                    {
                        var bg = ss.SetNumber % 2 == 0 ? "#F8FAFC" : White;

                        table.Cell().Background(bg).Padding(2).Text($"Set {ss.SetNumber}").FontSize(7).SemiBold();
                        NumCell(table, ss.ServeTot, bg);
                        NumCell(table, ss.ServeErr, bg);
                        NumCell(table, ss.ServePts, bg);
                        NumCell(table, ss.RecTot, bg);
                        NumCell(table, ss.RecErr, bg);
                        table.Cell().Background(bg).Padding(2).AlignCenter()
                            .Text(ss.RecTot > 0 ? $"{ss.RecPos * 100 / ss.RecTot}%" : ".").FontSize(7);
                        table.Cell().Background(bg).Padding(2).AlignCenter()
                            .Text(ss.RecTot > 0 && ss.RecExc > 0 ? $"({ss.RecExc * 100 / ss.RecTot}%)" : ".").FontSize(7);
                        NumCell(table, ss.AtkTot, bg);
                        NumCell(table, ss.AtkErr, bg);
                        NumCell(table, ss.AtkBlo, bg);
                        NumCell(table, ss.AtkPts, bg);
                        table.Cell().Background(bg).Padding(2).AlignCenter()
                            .Text(ss.AtkTot > 0 ? $"{ss.AtkPts * 100 / ss.AtkTot}%" : ".").FontSize(7);
                        NumCell(table, ss.BlkPts, bg);
                    }
                });

                // Coach info
                col.Item().PaddingTop(4).Text(t =>
                {
                    t.Span("Coach: ").FontSize(7).SemiBold();
                    t.Span(stats.CoachName).FontSize(7);
                    if (!string.IsNullOrEmpty(stats.AssistantCoach))
                    {
                        t.Span("  |  Assistant: ").FontSize(7).SemiBold();
                        t.Span(stats.AssistantCoach).FontSize(7);
                    }
                });
            });
        }

        private static void NumCell(TableDescriptor table, int value, string bg)
        {
            table.Cell().Background(bg).Padding(2).AlignCenter()
                .Text(value > 0 ? value.ToString() : ".").FontSize(7);
        }

        private static void NumCellBold(TableDescriptor table, int value)
        {
            table.Cell().Background(DarkBlue).Padding(2).AlignCenter()
                .Text(value > 0 ? value.ToString() : ".").FontSize(7).Bold().FontColor(White);
        }
    }
}
